### PR TITLE
Add missing Pillow dependencies to support openjpg and tiff scaling.

### PR DESCRIPTION
**Pull request by jladage**
Currently tiff or openjpeg images are not scaled by Pillow because of missing dependencies.

Also add lynx, wv and poppler-utils are needed to support transforms to text used for catalog indexing. When uploading a pdf or oldfashion .doc file of pdf the contents of those files is not added to the SearchableText index because poppler-utils and wc are missing.

Lynx is used to by a legacy transform from html to text which might still be used by add-ons. Although the lynx_dump transform should be removed, as long as that's not the case lynx should be available since it will break the transform.

### CODE REVIEW

**Comment by gforcada** [comment]
@jladage thanks for the pull request! Would you mind adding a changelog entry on [CHANGES.rst](https://github.com/plone/plone.docker/blob/master/CHANGES.txt)?

**Comment by gforcada** [comment]
@jladage if you think that the old transform that relies on lynx should be removed, would you mind to either create pull requests for that, or at least report it on [Products.CMFPlone issue tracker](https://github.com/plone/Products.CMFPlone/issues/new)?

**Comment by avoinea** [comment]
@jladage Shouldn't we also add these dependencies on Plone 4?

**Comment by avoinea** [comment]
@jladage Thanks! Can you also take a look at my comment on https://github.com/plone/plone.docker/commit/d4cb4fa647e32b90e243e209b67fb91982ea2dff

**Comment by jladage** [comment]
Hi @avoinea I added https://github.com/plone/Products.CMFPlone/issues/2026, added the dependencies to the latest plone 4 version and updated the Changelog.

**Pull request merged**
