### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by avoinea**
Every time and image is automatically built on docker-hub, the info at http://hub.docker.com/r/plone/plone is updated from this file.

### CODE REVIEW

**Comment by svx** [comment]
Hm .. this is so not compatible with our style guide and best practices .... :)

Can we please think about this, I know that you did that because that is how docker hub works with readmes, but I for example prefer pretty much another approach, like keeping a readme accoding to out best practices and linking there to the our main docs, with that we could have the best out of bold worlds, like we mention some of the new stuff like the tags in the readme, but the rest goes into the docs, I will give an example tomorrow, that will make it much more clear what I mean :)

**Comment by demarant** [comment]
indeed, the README could be shorter and pointing under the docs/<section> for more details on certain things. However I do like to keep a few docker run example and a single docker-compose example in the readme file.

**Comment by svx** [comment]
What is with something, like the following, it is by all means not finished yet, bust should be enough, to give an idea:

# plone.docker

[Plone](https://plone.org) is a free and open source content management system built on top of the Zope application server.


## Features

### Supported tags and respective `Dockerfile` links

- [`5.0.2`, `5.0`, `5`, `latest` (*5.0.2/Dockerfile*)](https://github.com/plone/plone.docker/blob/master/5.0/5.0.2/debian/Dockerfile)
- [`4.3.7`, `4.3`, `4` (*4.3.7/Dockerfile*)](https://github.com/plone/plone.docker/blob/master/4.3/4.3.7/debian/Dockerfile)
- [`5.0.2-alpine`, `5.0-alpine`, `5-alpine` (*5.0.2/alpine/Dockerfile*)](https://github.com/plone/plone.docker/blob/master/5.0/5.0.2/alpine/Dockerfile)
- [`4.3.7-alpine`, `4.3-alpine`, `4-alpine` (*4.3.7/alpine/Dockerfile*)](https://github.com/plone/plone.docker/blob/master/4.3/4.3.7/alpine/Dockerfile)

## Usage

### Start a Plone instance

```console
$ docker run -p 8080:8080 plone/plone
```

This image includes `EXPOSE 8080` (the Plone port), so standard container linking will make it automatically available to the linked containers. Now you can add a Plone Site at http://localhost:8080 - default Zope user and password are `admin/admin`.

### Start Plone as a ZEO client

Considering ZEO server is running at `192.168.1.1` on default port `8100` you can do:

```console
$ docker run -e ZEO_ADDRESS=192.168.1.1:8100 -p 8080:8080 plone/plone
```

or, using the ZEO Docker Image:

```console
$ docker run --name=zeo plone/zeoserver
$ docker run --link=zeo -e ZEO_ADDRESS=zeo:8100 -p 8080:8080 plone/plone
```

### Start Plone in debug mode

You can also start Plone in debug mode (`fg`) by running

```console
$ docker run -p 8080:8080 plone/plone fg
```
### Start a Plone instance

```console
$ docker run -p 8080:8080 plone/plone
```

This image includes `EXPOSE 8080` (the Plone port), so standard container linking will make it automatically available to the linked containers. Now you can add a Plone Site at http://localhost:8080 - default Zope user and password are `admin/admin`.

### Start Plone as a ZEO client

Considering ZEO server is running at `192.168.1.1` on default port `8100` you can do:

```console
$ docker run -e ZEO_ADDRESS=192.168.1.1:8100 -p 8080:8080 plone/plone
```

or, using the ZEO Docker Image:

```console
$ docker run --name=zeo plone/zeoserver
$ docker run --link=zeo -e ZEO_ADDRESS=zeo:8100 -p 8080:8080 plone/plone
```

### Start Plone in debug mode

You can also start Plone in debug mode (`fg`) by running

```console
$ docker run -p 8080:8080 plone/plone fg
```

For more information on how to extend this image with your own custom settings, adding more add-ons, building it or mounting volumes, please refer to our [documentation](https://github.com/plone/plone.docker/tree/master/docs).



## Documentation

Full documentation for end users can be found in the ["docs"]((https://github.com/plone/plone.docker/tree/master/docs) folder.
It is also available online at http://docs.plone.org/foo/bar


## Contribute


- Issue Tracker: github.com/collective/collective.fancystuff/issues
- Source Code: github.com/collective/collective.fancystuff
- Documentation: docs.plone.org/foo/bar

## Support


If you are having issues, please let us know.
We have a mailing list located at: project@example.com

## License

The project is licensed under the GPLv2.

**Comment by demarant** [comment]
@sven from my side, that looks ok, without the repetition of course, see the multiple sections you have in the example above, i guess a double copy and paste :)

**Comment by svx** [comment]
@demarant yeah this was a mistake and ther are still some typos, will fix that asap :)

**Comment by avoinea** [comment]
Updated with @svx suggestions.

**Comment by svx** [comment]
Awesome ! Thanks !

**Pull request merged**
