### PR TITLE
Refs #13 - Alpine/Debian Dockerfiles for Plone 4.3.7/5.0.2 based on Plone Unified Installer

### PR DESCRIPTION
**Pull request by avoinea**
A first pull request to discuss on it.

Image sizes (the best I could get):
```
plone     5-alpine            4da089f80d0a        4 seconds ago       308.9 MB
plone     5-debian            1c45fbc05d61        7 minutes ago       430 MB
plone     4-alpine            8e405b90d01f        24 minutes ago      232.3 MB
plone     4-debian            65d7633c4607        2 minutes ago       353.7 MB
```

Known bugs (any help here will be appreciated):
* `Plone 5 on Alpine` starts but when I try to add Plone site, Zope crashes with no message: `error code: 245`. It works fine with Plone 4.

The README and examples will come after we agree on this.

Quick usage examples:

* Default action (start & logtail)
``` 
$ docker run -p 8080:8080 plone
```

* Debug mode
``` 
$ docker run -p 8080:8080 plone fg
```

* It actually supports all `instance` commands:
``` 
$ docker run plone help
```

### CODE REVIEW

**Comment by avoinea** [comment]
@bloodbare I moved your code to 5.0.2-custom. As the new image covers your scenario, please let us know if we should still keep it, or we can safely remove it.

**Comment by demarant** [comment]
@svx 
could you please come back with any comments you may have to this initial PR?
so that @avoinea can continue the work started

**Comment by svx** [comment]
@avoinea looks good to me, I still do not get the code: 245, did you tried it on alpine edge, too ? could be a version thing of a package, here Plone 5 is running fine on alpine

**Comment by svx** [comment]
@avoinea want me to merge ?

**Comment by demarant** [comment]
@svx yes, we would like a second eye on this first PR :) from there maybe not so many PR will be necessary, but this one it is good.

**Comment by svx** [comment]
@bloodbare would you mind to check docker hub and change the auto build to the new directory [ 5.0.2-custom ] so that we do not break your setup ?

**Comment by bloodbare** [comment]
I'm going to merge today if its ok, just need to be sure that my setup is not broken before

**Pull request merged**
